version: '3.3'
services:
  application: 
    build: .
    ports: 
     - "8080:8080"
    depends_on:
        database:
         condition: service_healthy
  database:
    build: ./datarapid-docs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports: 
      - "3306:3306"
    expose:
      - "3306"
